language: csharp
mono: none
os: linux
dist: trusty
dotnet: 2.0.0
script: dotnet nuget push src/BackpackTfApi/bin/Release/BackpackTfApi.***.nupkg --api-key
  $NUGET_API_KEY
deploy: 
skip_cleanup: true
provider: script
true:
  tags: true
  condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
    secure: XcBAApoOz42t+SzImdDvj8Pf44ykZ3ajrgniHwhJwE0cub19DaveRCn/Y++DaEaT6cjgbig9pZq46S4+ch14DvuqoTM5qi/kriWArLK9EXkUKvMQbIUo1DnbNXUf/hbkHe6qduCQZOieq/O6uh0t4iIZm1xz3E00jv050K7KNc5toja577isuLzcfB3zXoWsXI1NYoEyg6ewxp04NTrjVlxhN4vVf3h2LGyzdaA/dgIXQKCKHeHDeh/wR6G8wH85ucL4A+gZz+Ac8FPZi/U96m+8O5mqZG5qwOL5I496fnwli4JMD2ibJ2azEv8fKp1Qv9QkV9wUnJbmTGOEWHx6ISOqx2IjGd1fPWgHRkEAy23kDvXC3Zoc6xob69REld22bkUaQSTn1pwoCxX/makquWqpLFZL7CJzKmIyl9dB0iC+SK1F2qaOLcNoiui2Vfa28O7MFabjsVYwRuYNs9Vos7tBl6E7QygSLriydRKuii965b/vai55W/rUi52N0UqLgwRa6Qq3825R7tBHHLjAyyLoEsr6fQ17rcrUl4/pPf0PAqPdAURlFb0Nf4zOdLqWyFCru8geRYZstzgoFFXTJTcA15LXydWFmoLRYn+Iw3y9/+jdAOoJvMX9UU0+eG18n3C/1XtGcfJ0nKmoEd3U4O9QaGToRBQu0NJV7EoUIuE=
