language: csharp
mono: none
os: linux
dist: trusty
dotnet: 2.0.0
script: dotnet nuget push src/BackpackTfApi/bin/Release/BackpackTfApi.***.nupkg --api-key
  NUGET_API_KEY
deploy: 
skip_cleanup: true
provider: script
true:
  tags: true
  condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
    secure: UJNhFHv8uaDK5sYPCiMxXJuKGYLYqF7QIkq8ZQx+jwdy3x5keKzWBRQ1bipubXf/Fobf/V/HAdy5dfwbQJ+Bvsib/Z2rUnpNnnumpzpw3P3tm7f7eBnTIC/9gd6ykOSIvmp6b6AtUidukwSbvQisTVUZHhMHIw7p83U7yuRtSSqDrsenEgR1J7+4FVrXcJGJtaxjmg2iymosLImKrdl3AhpgxY3VxZ5ngMz0mEPTPO2NgGHfULgT570MD2/3AH7tjHrqNoFoqLJnumWbZzxBjA/RnPZZ8jo1qrQpD64DUzHyI4x5LJLIETIFmmOTOxKFJ4XM0gazi8q70JMFZxBRvDUIxw2XqWX3IjcVHskfLIQ3XrZTcaNTtE4PUPzyF7GV0OHDloMi/pGcQQyZCzwXO6kyKlrgUW14d9sVllVsfENs8mLkFtqQwp3cadh4+m9a4WdOF/1DO/MT6marOMWfHNkfy06VmSFMPpYtICaqN5uVSybeTF85FS008hhd8bW/gUd4P9gi4Kqb90v/VlD+WeweWISAKCqrMEub5YrLt8moS9YT1FRGZwS0fyCTv1LjIpTdkODraylfL8LIHd3xhgALBhHOe3+WnAD9Wdjm9mT4z9U5hWGL8ukrWSBMxs75wC/t3ZlLUKd9RNiA48E2aRQxtLfxnJIO67nFDuzgUlY=
