language: csharp
mono: none
os: linux
dist: trusty
dotnet: 2.0.0
script: dotnet nuget push src/BackpackTfApi/bin/Release/BackpackTfApi.***.nupkg --api-key
  NUGET_API_KEY
deploy: 
skip_cleanup: true
provider: script
true:
  tags: true
  condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
    secure: fpnLT73AncKGpjnGGrFcqUyRK2lXrWu8Lqmh1Vw6EK2CvBrQ7MVbs3rNlSWe+kDLYc2GoiAW/KVUfpTJg86NhNQoQeZdf1DnMqDsmiAdkb/AI74yODi7OXqd7zt6cVJmagO3bs6RM3t90CcxgB4rIS0LrFE3U7yEWMRHSDhGpY9LATpOerHEnxHVJBfbkxsMT/i82GeCpEFwtl93+uNquyk9WosPVjCITHqheFwc7HW9rieEnNc3Obl6NrUJhOfn6jd7QasWoK8hcEWR+hRky5cga0Pke0hDDpjogh1RaKzRiO3X/W7Vzz9WuMbsOiqJ5b25byUJfq3elcfIeT9iLJnnfcJ65BYc7xiB1Wu4fpW2HLBD/oDZsAyZTi4scAwBR7ZYUBJZyrOOrzQ41wGIB7XbUWrVTHwxR1ZBJ2JLtTV14sWHdI5UXzUKq7DqeHnQ71MmuY+yxE984VLmvtnpHTGocDeG8KxdXcL++vTQjNPakn8Tedh2nVIbF6mpHnALDHU3RtYjAnPbJ7LyepUjGD4qWzQP+nS4DbcpJph21oPX2Qm+33QzgtIpUj6KZwJtGH+6i1zMVGrtLiWk309BmFueZMdCggbwTV4BhMKT9MySaYqS3b3ay5oWlZQ7Q9d9D4xxI8hhy43exhH+5M1nnX3ZxxyE+4E/1FKG2DwiBWk=
