language: csharp
mono: none
os: linux
dist: trusty
dotnet: 2.0.0
script: dotnet nuget push src/BackpackTfApi/bin/Release/BackpackTfApi.***.nupkg --api-key
  NUGET_API_KEY
deploy: 
skip_cleanup: true
provider: script
true:
  tags: true
  condition: "$TRAVIS_TAG =~ ^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
env:
  global:
    secure: fbzAAlD0O/MVjvW1jb46296WyG8vOp+lfZWIWfziOEsnb0c8ofPg+iWF41gI9Gb5eb3FMnT/LVDksZB6V9/phC1tb/riyS9anD5/Q3kqkHhSDW2rfNikCbv/DEeTT5KCA2bu9ssm7NTyzA/fFvTl8Bthv5RNP0iz/Iecob2xvMODmNmlT95ghX/xzr1hfglbJ1ZOQpdsUwy3oUtW1DC3wG1/fTea9MsiL+2Rna1Yr7pUUEKPmPKMa2jyIxnoX1Rgue6NNi07fJoio782thvRf9pXQ8xOgoOAE/OMy62URTTkkLI3Oj4GhUGTNvyO+pKxugmoVauUsON5VUe1RZEZNuVolMBwpZgq65Q4cocL3RYIoxSBo50oPiwV8ct9bOaejo5KAkMQcqFAIIjG9qmaNhmp1RTR4znQgzwUmbMdg8FzUyWbioS5bmcEETv6PAwRhxl3dMJ90VBDKszDtiaLcU0KrUYtCxcvnNDnQ60FOLyl8rJVWBd/GIphL5dKjmoJYY8oZiHst7EsjnJtjNPA3hcBf0o4LFxKsP5RjkKInyW0az0bDO8lRufZLiKoUoF/rBhDYcmGOdnvk3M21m3EjzufJ31sVrgcKc+BjIHnf/CHjIzdAew3CDvBfHkLUYazZCS2qASrEzMRTA7spGIU8AiZTmx4Hqlm24Iv6iD4koo=
